spring:
  application:
    name: transactionService
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
sepay:
  api-key: {SEPAY_API_KEY}


